### PR TITLE
Fix spelling mistakes in OMRProcessorArchitecture enum

### PR DESCRIPTION
**Pull request by ThanHenderson**
For `RISCV32` and `RISCV64` enum variants in `OMRProcessorArchitecture`, 'processor' was spelt 'procesor'. This patch fixes the spelling.

Signed-off-by: Nathan Henderson <nathan.henderson@ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
@ThanHenderson OMR changes go in [eclipse/omr](https://github.com/eclipse/omr). [eclipse-openj9/openj9-omr](https://github.com/eclipse-openj9/openj9-omr) mirrors [eclipse/omr](https://github.com/eclipse/omr) for the OpenJ9 project. Changes from [eclipse/omr](https://github.com/eclipse/omr) flow into [eclipse-openj9/openj9-omr](https://github.com/eclipse-openj9/openj9-omr) after an [OMR acceptable build](https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance) succeeds/promotes.

**Comment by babsingh** [comment]
There are similar typos in the OpenJ9 repo: https://github.com/eclipse-openj9/openj9/blob/473f1e9efe0f43c0745999ebedb4b5392f7bb199/runtime/oti/j9port.h#L396-L398.

**Comment by ThanHenderson** [comment]
@babsingh I'll close this issue and open in `eclipse/omr` instead. Thanks.

Yes, I've opened a PR about that too: https://github.com/eclipse-openj9/openj9/pull/18916

**Comment by ThanHenderson** [comment]
Opened https://github.com/eclipse/omr/pull/7255  in proper location. Closing this.

**Pull request closed without merging**
