### PR TITLE
(0.46) x86-64: Use rep movs instructions if array copy size greater than 32 bytes

### PR DESCRIPTION
**Pull request by a7ehuo**
This PR ports https://github.com/eclipse/omr/pull/7384 to v0.46

----
This change applies to byte and char array System.arraycopy sequence. It avoids using vector instructions for copy size between 32 bytes to 64 bytes due to an observed regression.

### CODE REVIEW

**Comment by a7ehuo** [comment]
@0xdaryl @vijaysun-omr @ymanton @hzongaro fyi

**Comment by 0xdaryl** [comment]
This needs to wait until eclipse/omr#7384 promotes and passes OMR acceptance.

@pshipton : for awareness and concerns

**Comment by a7ehuo** [comment]
There are some failures from the OMR acceptance build: https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/707/, which look to me are known issues 

**aarch64_linux jdk 11 sanity.openjdk**: `jdk_security4_0_failed`
- https://github.com/eclipse-openj9/openj9/issues/18980

**ppc64_aix jdk 17 sanity.openjdk**: `jdk_lang_VarHandleTest_j9_1_FAILED`, `jdk_lang_VarHandleTest_j9_0_FAILED`
- `java.lang.AssertionError: No throwable thrown. Expected class java.nio.ReadOnlyBufferException expected object to not be null`
- https://github.com/eclipse-openj9/openj9/issues/19693

**s390x_linux jdk 17 sanity.openjdk**: `jdk_lang_VarHandleTest_j9_0_FAILED`, `jdk_lang_VarHandleTest_j9_1_FAILED`
- `java.lang.AssertionError: No throwable thrown. Expected class java.nio.ReadOnlyBufferException expected object to not be null`
- https://github.com/eclipse-openj9/openj9/issues/19693

**Comment by pshipton** [comment]
I already promoted the OMR acceptance build earlier today.

**Pull request merged**
